### ISSUE TITLE
Password request action doesn't work 

### ISSUE THREAD

**Issue by ascheider** [pimcore-extensions/member#3]
passwordRequestAction throws excepttion on form submit:
Call to undefined method requestPasswordReset in class Pimcore\Model\Object\Member

  $list = \Member::getByEmail($email);
            if (count($list) == 0) {
                $this->view->error = $this->translate->_('member_password_request_email_not_exist');
                return;
            }
            /** @var \Member $member */
            $member = $list->current();
            $member->requestPasswordReset();

Pimcore\Model\Object\Member class has no requestPasswordReset method

**Comment by dpfaffenbauer** [comment]
I guess this plugin is kinda deprecated and abandoned. Not sure if @Hagith is gonna fix anything here. I suggest you have a look at the newer one: https://github.com/dachcom-digital/pimcore-members

**Comment by Hagith** [comment]
Yeah, I can't name myself a php programmer for a few years now. Good to see that pimcore is still in active development and there is a good looking alternative for this plugin :)
